# Generated by Django 4.1.7 on 2023-03-31 13:12

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('path', models.FileField(upload_to='datasets')),
                ('features', models.JSONField(default=dict)),
                ('targets', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Decision Tree Classifier', 'Decision Tree Classifier'), ('K-Nearest Neighbors Classifier', 'K-Nearest Neighbors Classifier'), ('Logistic Regression', 'Logistic Regression'), ('Gaussian Naive Bayes Classifier', 'Gaussian Naive Bayes Classifier'), ('Random Forest Classifier', 'Random Forest Classifier'), ('Support Vector Machine', 'Support Vector Machine')], default='K-Nearest Neighbors Classifier', max_length=50)),
                ('model_obj', models.FileField(null=True, upload_to=pathlib.PureWindowsPath('D:/Projectz/Insight/backend/static/media/saved_models'))),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
        ),
    ]
