# Generated by Django 4.1.7 on 2023-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='targets',
            field=models.JSONField(default=dict),
        ),
    ]
