# Generated by Django 4.1.7 on 2023-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_modelfile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(max_length=24, null=True, unique=True, verbose_name='API key'),
        ),
    ]
